# sample-standalone

Vagrant.configure("2") do |config|    
    config.vm.box = "hashicorp/bionic64"
    (1..3).each do |i|
        config.vm.define "vpc#{i}" do |vpc|
            vpc.
            vpc.vm.hostname = "vpc#{i}"
            vpc.vm.network "private_network", ip: "192.168.56.1#{i}"
        end
      end
end