# sample-cluster

Vagrant.configure("2") do |config|    
    config.vm.box = "hashicorp/bionic64"
    (1..3).each do |i|
        config.vm.define "node-#{i}" do |vpc|
            if i == 1
                vpc.vm.network "forwarded_port", guest: 80, host: 8080
            elsif i == 2
                vpc.vm.network "forwarded_port", guest: 80, host: 8081
            else
                vpc.vm.network "forwarded_port", guest: 80, host: 8082
            end
        end
    end
end