Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64" 

  if Vagrant.has_plugin?("vagrant-cachier") 
        config.cache.scope = :box 
  end

   # configure zookeeper cluster

    (1..3).each do |i|
       config.vm.define "zookeeper-#{i}" do |s|
          s.vm.hostname = "zookeeper-#{i}"
          s.vm.network "private_network", ip: "192.168.50.10#{i}"
          s.vm.provision :shell, path: "install.sh", :args => ["192.168.50.10", "#{i}"]
       end
    end
end
