# sample-standalone

Vagrant.configure("2") do |config|    
    config.vm.box = "hashicorp/bionic64"
    (1..3).each do |i|
        config.vm.define "node-#{i}" do |vpc|
            vpc.vm.hostname = "node-#{i}"
            vpc.vm.network "private_network", type:"dhcp"
        end
      end
end