Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "flink-alone"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.provision :shell, path: "install.sh"

end
