# sample-standalone

Vagrant.configure("2") do |config|    
    config.vm.box = "hashicorp/bionic64"
    (1..3).each do |i|
        config.vm.define "node-#{i}" do |vpc|
            vpc.vm.hostname = "node-#{i}"
            vpc.vm.network "public_network", ip: "192.168.1.10#{i}"
        end
      end
end